objects-y+=test.o uart.o ap.o helpers.o
objects-y+=microrl.o
objects-y+=console.o

objects-y+=cmd_iw.o
objects-y+=cmd_ifconfig.o
objects-y+=cmd_common.o
objects-y+=cmd_gpio.o
objects-y+=cmd_flash.o
objects-y+=cmd_listen.o
#objects-y+=cmd_poke.o
objects-y+=cmd_env.o
objects-y+=env.o

subdirs-y+=netapps/
